name: 'Docker'
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login
        uses: azure/docker-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}
          login-server: 'docker.pkg.github.com'

      - name: build and push
        run: |
          test $(git log -1 --pretty=%B) = "release: version" && VERSION=$(sed -nE 's/^\s*"version": "(.*?)",$/\1/p' package.json) || VERSION="latest"
          docker build -t docker.pkg.github.com/iiabady/zkrapp/app:$VERSION .
          docker push docker.pkg.github.com/iiabady/zkrapp/app:$VERSION
      - name: Logout
        uses: azure/container-actions/docker-logout@master