name: Lint
on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: ESLint
      uses: iCrawl/action-eslint@v1
      env:
        FOLDERS: src
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
